import simpleGit from "simple-git";

export async function pushRepo(localPath: string, repoUrl: string) {
  const git = simpleGit(localPath);

  // Initialize repo
  await git.init();

  // Configure author
  await git.addConfig("user.name", "Wadi Bot");
  await git.addConfig("user.email", "bot@wadi.ai");

  // Add all files
  await git.add(".");

  // Commit
  await git.commit("Initial commit generated by Wadi Blueprint Builder");

  // Force default branch to main
  await git.branch(["-M", "main"]);

  // Add remote
  await git.addRemote("origin", repoUrl);

  // Push
  await git.push(["-u", "origin", "main"]);
}
