import { useParams, Link } from "react-router-dom";
import { useProjectPRs } from "../hooks/useFounder";
import { GitPullRequest, CheckCircle, Clock, ExternalLink, ArrowLeft, GitMerge } from "lucide-react";

export default function ProjectPRs() {
  const { id } = useParams();
  const { data: prs, isLoading } = useProjectPRs(id!);

  return (
    <div className="max-w-4xl mx-auto py-8 text-wadi-text animate-in slide-in-from-bottom-2 fade-in">
      <header className="mb-8 flex items-center gap-4">
        <Link to={`/projects/${id}`} className="text-gray-400 hover:text-black transition-colors rounded-full hover:bg-gray-100 p-2">
           <ArrowLeft size={20} />
        </Link>
        <div>
           <h1 className="text-2xl font-bold flex items-center gap-2">
             <GitPullRequest className="text-purple-600" />
             AI Pull Requests
           </h1>
           <p className="text-gray-500 text-sm mt-1">
             Ramas y mejoras de código propuestas autogeneradas por el AI Engine.
           </p>
        </div>
      </header>
      
      {isLoading ? (
        <div className="flex flex-col gap-4 animate-pulse pt-4">
            <div className="h-20 bg-gray-50 border rounded-xl" />
            <div className="h-20 bg-gray-50 border rounded-xl" />
        </div>
      ) : prs && prs.length > 0 ? (
        <div className="space-y-4">
            {prs.map((pr: { id: string, insight_id?: string, pr_url: string, status: string, created_at: string, title?: string }) => (
                <PRCard key={pr.id} pr={pr} />
            ))}
        </div>
      ) : (
         <div className="text-center p-12 border border-dashed rounded-xl bg-gray-50 mt-8">
             <CheckCircle size={40} className="mx-auto text-gray-300 mb-4" />
             <h3 className="font-bold text-lg mb-1">Sin Pull Requests pendientes</h3>
             <p className="text-gray-500 text-sm">El AI Engine creará un PR aquí cuando evolucione el código.</p>
         </div>
      )}
    </div>
  );
}

function PRCard({ pr }: { pr: { id: string, insight_id?: string, pr_url: string, status: string, created_at: string, title?: string }}) {
   const isMerged = pr.status === 'merged';
   const isClosed = pr.status === 'closed';
   const isOpen = pr.status === 'open' || pr.status === 'generated';
   
   return (
       <div className={`p-5 rounded-xl border flex gap-4 items-center ${isMerged || isClosed ? 'bg-gray-50 border-gray-200' : 'bg-white border-purple-200 shadow-sm hover:shadow-md transition-shadow'}`}>
          <div className="shrink-0 p-2 rounded-full bg-white border">
             {isMerged ? <GitMerge className="text-purple-600" size={20} /> : isOpen ? <GitPullRequest className="text-green-600" size={20} /> : <GitPullRequest className="text-gray-400" size={20} />}
          </div>
          <div className="flex-1">
              <div className="flex items-center gap-3 mb-1">
                  <h3 className="text-lg font-bold text-gray-900 line-clamp-1">{pr.title || `Autogenerated Evolution PR`}</h3>
                  <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full uppercase tracking-wider ${isMerged ? 'bg-purple-100 text-purple-700' : isOpen ? 'bg-green-100 text-green-700' : 'bg-gray-200 text-gray-600'}`}>
                      {pr.status}
                  </span>
              </div>
              <p className="text-xs text-gray-500 font-medium flex items-center gap-1">
                 <Clock size={12} /> {new Date(pr.created_at).toLocaleString()}
              </p>
          </div>
          <div className="shrink-0">
              <a 
                href={pr.pr_url} 
                target="_blank" 
                rel="noreferrer"
                className={`px-4 py-2 rounded-lg text-sm font-bold flex items-center gap-2 transition-colors ${isOpen ? 'bg-black text-white hover:bg-gray-800' : 'bg-white border text-gray-700 hover:bg-gray-50'}`}
              >
                  Review <ExternalLink size={14} />
              </a>
          </div>
       </div>
   );
}
