-- Migration: WADI v1.1 PRD and Terminal Commands
-- Adds prd column and ensures structure can hold terminal_commands
ALTER TABLE projects
ADD COLUMN IF NOT EXISTS prd text;
-- Add comment for documentation
COMMENT ON COLUMN projects.prd IS 'Technical Product Requirements Document generated by WADI';
-- Ensure structure column (jsonb) exists (it should, but just in case)
-- We don't need a specific schema change for jsonb fields usually,
-- but we can add a check or keep it flexible as the Zod schema in the API handles validation.
-- Optional: track if a project has been materializing with a specific orientation
ALTER TABLE projects
ADD COLUMN IF NOT EXISTS orientation text DEFAULT 'technical';
COMMENT ON COLUMN projects.orientation IS 'Project orientation: technical or business';